<?php
$files = [];

// Enums
$files['app/Domain/Enums/TaskStatus.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum TaskStatus: string {\n    case Draft = 'draft';\n    case Assigned = 'assigned';\n    case InProgress = 'in_progress';\n    case SubmittedForReview = 'submitted_for_review';\n    case UnderReview = 'under_review';\n    case Approved = 'approved';\n    case NeedsRework = 'needs_rework';\n    case Cancelled = 'cancelled';\n}\n";
$files['app/Domain/Enums/TaskPriority.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum TaskPriority: string {\n    case Low = 'low';\n    case Normal = 'normal';\n    case High = 'high';\n    case Urgent = 'urgent';\n}\n";
$files['app/Domain/Enums/ApprovalType.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum ApprovalType: string {\n    case Technical = 'technical';\n    case Final = 'final';\n}\n";
$files['app/Domain/Enums/ApprovalStatus.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum ApprovalStatus: string {\n    case Approved = 'approved';\n    case Rejected = 'rejected';\n    case NeedsRework = 'needs_rework';\n}\n";
$files['app/Domain/Enums/WeightChangeRequestStatus.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum WeightChangeRequestStatus: string {\n    case Pending = 'pending';\n    case Approved = 'approved';\n    case Rejected = 'rejected';\n}\n";
$files['app/Domain/Enums/SlaType.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum SlaType: string {\n    case Response = 'response';\n    case Resolution = 'resolution';\n}\n";
$files['app/Domain/Enums/SlaStatus.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum SlaStatus: string {\n    case Active = 'active';\n    case Paused = 'paused';\n    case Stopped = 'stopped';\n}\n";
$files['app/Domain/Enums/SlaEventType.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum SlaEventType: string {\n    case Start = 'start';\n    case Pause = 'pause';\n    case Resume = 'resume';\n    case Stop = 'stop';\n    case Breach = 'breach';\n}\n";
$files['app/Domain/Enums/DurationUnit.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum DurationUnit: string {\n    case Days = 'days';\n    case Weeks = 'weeks';\n    case Months = 'months';\n}\n";
$files['app/Domain/Enums/DependencyType.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum DependencyType: string {\n    case Fs = 'fs';\n}\n";
$files['app/Domain/Enums/SyncStatus.php'] = "<?php\n\nnamespace App\\Domain\\Enums;\n\nenum SyncStatus: string {\n    case Pending = 'pending';\n    case Synced = 'synced';\n    case Failed = 'failed';\n}\n";

// Exceptions
$baseEx = "<?php\n\nnamespace App\\Domain\\Exceptions;\n\nuse Exception;\n\nclass DomainException extends Exception {}\n";
$files['app/Domain/Exceptions/DomainException.php'] = $baseEx;
foreach(['InvalidTaskTransitionException', 'UnauthorizedTaskOperationException', 'ContractorScopeViolationException', 'TaskAlreadyApprovedException', 'PendingRequestExistsException', 'DuplicatePeriodException', 'InvalidWeightException', 'SlaAlreadyStartedException', 'SlaAlreadyStoppedException', 'InvalidApprovalException'] as $ex) {
    $files["app/Domain/Exceptions/{$ex}.php"] = "<?php\n\nnamespace App\\Domain\\Exceptions;\n\nclass {$ex} extends DomainException {}\n";
}

// DTO
$files['app/Domain/DTOs/CreateTaskData.php'] = "<?php\n\nnamespace App\\Domain\\DTOs;\n\nuse App\\Domain\\Enums\\TaskPriority;\n\nreadonly class CreateTaskData {\n    public function __construct(\n        public int \$project_id,\n        public ?int \$wbs_phase_id,\n        public string \$title,\n        public ?string \$description,\n        public TaskPriority \$priority,\n        public float \$weight,\n        public ?string \$planned_start_date,\n        public ?string \$planned_due_date,\n        public ?int \$parent_task_id\n    ) {}\n}\n";

// State Transition
$files['app/Domain/Rules/TaskStateTransition.php'] = "<?php\n\nnamespace App\\Domain\\Rules;\n\nuse App\\Domain\\Enums\\TaskStatus;\nuse App\\Domain\\Exceptions\\InvalidTaskTransitionException;\n\nclass TaskStateTransition {\n    protected array \$allowedTransitions = [\n        'draft' => ['assigned', 'cancelled'],\n        'assigned' => ['in_progress', 'cancelled'],\n        'in_progress' => ['submitted_for_review', 'cancelled'],\n        'submitted_for_review' => ['under_review'],\n        'under_review' => ['approved', 'needs_rework'],\n        'needs_rework' => ['in_progress', 'cancelled'],\n        'approved' => [],\n        'cancelled' => [],\n    ];\n\n    public function canTransition(TaskStatus \$from, TaskStatus \$to): bool {\n        if (\$from === \$to) return false;\n        return in_array(\$to->value, \$this->allowedTransitions[\$from->value] ?? []);\n    }\n\n    public function assertCanTransition(TaskStatus \$from, TaskStatus \$to): void {\n        if (!\$this->canTransition(\$from, \$to)) {\n            throw new InvalidTaskTransitionException(sprintf('Cannot transition task from %s to %s', \$from->value, \$to->value));\n        }\n    }\n}\n";

// Contractor Scope Rule
$files['app/Domain/Rules/TaskScopeService.php'] = "<?php\n\nnamespace App\\Domain\\Rules;\n\nuse App\\Models\\Task;\nuse App\\Models\\User;\nuse App\\Domain\\Exceptions\\ContractorScopeViolationException;\n\nclass TaskScopeService {\n    public function assertCanAccess(Task \$task, User \$actor): void {\n        // Example check: if actor is a contractor, ensure task belongs to their contractor_id.\n        if (\$actor->contractor_id !== null && \$task->contractor_id !== \$actor->contractor_id) {\n            throw new ContractorScopeViolationException('Contractor does not have access to this task.');\n        }\n    }\n\n    public function assertCanActAsAssignedContractor(Task \$task, User \$actor): void {\n        // Needs concrete implementation\n    }\n\n    public function assertCanManageContract(Task \$task, User \$actor): void {\n        // Needs concrete implementation\n    }\n}\n";

// Audit Contract
$files['app/Domain/Contracts/AuditServiceInterface.php'] = "<?php\n\nnamespace App\\Domain\\Contracts;\n\nuse Illuminate\\Database\\Eloquent\\Model;\nuse App\\Models\\User;\nuse App\\Models\\ActivityLog;\n\ninterface AuditServiceInterface {\n    public function log(\n        string \$action,\n        Model \$entity,\n        User \$actor,\n        array \$oldValues = [],\n        array \$newValues = [],\n        array \$metadata = []\n    ): ActivityLog;\n}\n";

// Unit Tests
$files['tests/Unit/Domain/TaskStatusTest.php'] = "<?php\n\nnamespace Tests\\Unit\\Domain;\n\nuse PHPUnit\\Framework\\TestCase;\nuse App\\Domain\\Enums\\TaskStatus;\n\nclass TaskStatusTest extends TestCase {\n    public function test_task_status_values() {\n        \$this->assertEquals('draft', TaskStatus::Draft->value);\n        \$this->assertEquals('assigned', TaskStatus::Assigned->value);\n        \$this->assertEquals('in_progress', TaskStatus::InProgress->value);\n        \$this->assertEquals('submitted_for_review', TaskStatus::SubmittedForReview->value);\n        \$this->assertEquals('under_review', TaskStatus::UnderReview->value);\n        \$this->assertEquals('approved', TaskStatus::Approved->value);\n        \$this->assertEquals('needs_rework', TaskStatus::NeedsRework->value);\n        \$this->assertEquals('cancelled', TaskStatus::Cancelled->value);\n    }\n}\n";

$files['tests/Unit/Domain/TaskStateTransitionTest.php'] = "<?php\n\nnamespace Tests\\Unit\\Domain;\n\nuse PHPUnit\\Framework\\TestCase;\nuse App\\Domain\\Enums\\TaskStatus;\nuse App\\Domain\\Exceptions\\InvalidTaskTransitionException;\nuse App\\Domain\\Rules\\TaskStateTransition;\n\nclass TaskStateTransitionTest extends TestCase {\n    protected TaskStateTransition \$transition;\n\n    protected function setUp(): void {\n        parent::setUp();\n        \$this->transition = new TaskStateTransition();\n    }\n\n    public function test_valid_transitions() {\n        \$this->assertTrue(\$this->transition->canTransition(TaskStatus::Draft, TaskStatus::Assigned));\n        \$this->assertTrue(\$this->transition->canTransition(TaskStatus::Assigned, TaskStatus::InProgress));\n        \$this->assertTrue(\$this->transition->canTransition(TaskStatus::UnderReview, TaskStatus::NeedsRework));\n        \$this->assertTrue(\$this->transition->canTransition(TaskStatus::NeedsRework, TaskStatus::InProgress));\n    }\n\n    public function test_invalid_transitions() {\n        \$this->assertFalse(\$this->transition->canTransition(TaskStatus::Draft, TaskStatus::InProgress));\n        \$this->assertFalse(\$this->transition->canTransition(TaskStatus::Approved, TaskStatus::Assigned));\n        \$this->assertFalse(\$this->transition->canTransition(TaskStatus::Cancelled, TaskStatus::Draft));\n    }\n\n    public function test_same_state_transition_is_invalid() {\n        \$this->assertFalse(\$this->transition->canTransition(TaskStatus::Draft, TaskStatus::Draft));\n    }\n\n    public function test_assert_throws_exception() {\n        \$this->expectException(InvalidTaskTransitionException::class);\n        \$this->transition->assertCanTransition(TaskStatus::Draft, TaskStatus::InProgress);\n    }\n}\n";

$files['tests/Unit/Domain/CreateTaskDataTest.php'] = "<?php\n\nnamespace Tests\\Unit\\Domain;\n\nuse PHPUnit\\Framework\\TestCase;\nuse App\\Domain\\DTOs\\CreateTaskData;\nuse App\\Domain\\Enums\\TaskPriority;\n\nclass CreateTaskDataTest extends TestCase {\n    public function test_create_task_data() {\n        \$dto = new CreateTaskData(\n            1,\n            null,\n            'Test Task',\n            null,\n            TaskPriority::Normal,\n            10.5,\n            null,\n            null,\n            null\n        );\n\n        \$this->assertEquals(1, \$dto->project_id);\n        \$this->assertEquals('Test Task', \$dto->title);\n        \$this->assertEquals(TaskPriority::Normal, \$dto->priority);\n        \$this->assertObjectNotHasProperty('contract_id', \$dto);\n        \$this->assertObjectNotHasProperty('status', \$dto);\n    }\n}\n";

$files['tests/Unit/Domain/TaskScopeServiceTest.php'] = "<?php\n\nnamespace Tests\\Unit\\Domain;\n\nuse Tests\\TestCase;\nuse App\\Domain\\Rules\\TaskScopeService;\nuse App\\Models\\Task;\nuse App\\Models\\User;\nuse App\\Domain\\Exceptions\\ContractorScopeViolationException;\n\nclass TaskScopeServiceTest extends TestCase {\n    public function test_contractor_can_access_own_task() {\n        \$service = new TaskScopeService();\n        \$user = new User(['contractor_id' => 1]);\n        \$task = new Task(['contractor_id' => 1]);\n\n        \$service->assertCanAccess(\$task, \$user);\n        \$this->assertTrue(true);\n    }\n\n    public function test_contractor_cannot_access_other_task() {\n        \$service = new TaskScopeService();\n        \$user = new User(['contractor_id' => 1]);\n        \$task = new Task(['contractor_id' => 2]);\n\n        \$this->expectException(ContractorScopeViolationException::class);\n        \$service->assertCanAccess(\$task, \$user);\n    }\n}\n";

foreach (\$files as \$path => \$content) {
    file_put_contents(__DIR__ . '/' . \$path, \$content);
}
echo "All files generated successfully.";
